config/routes.rb
Rails.application.routes.draw do

 #  devise_scope :user do
 #   get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
 #   get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
 # end
  # devise_for :users

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }



  # devise_for :users, controllers: {
  #       sessions: 'users/sessions'
  #     }

  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  root to: 'home#index'

  resources :users do
    resources :images
  end

  resources :images do
    resources :comments
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates :name, :description, :presence => true
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!, :only => [:new]

  before_action :only => [:edit] do
    redirect_to '/' unless is_admin? || is_current_user?
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @image = @user.images.new
  end

  def create
    @user = User.find(params[:user_id])
    @image = @user.images.new(image_params)
    if @image.save
      redirect_to user_path(@image.user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @image = Image.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @image = Image.find(params[:id])
    if @image.update(image_params)
      redirect_to user_path(@image.user)
    else
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to user_path(@image.user)
  end

  private
  def image_params
    params.require(:image).permit(:name, :description, :avatar)
  end
end

app/views/images/_form.html.erb
<%= render 'layouts/errors', :object => @image %>

<%= form_for [@user, @image] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.file_field :avatar %>
  <p><%= f.submit %></p>
<% end %>

app/views/images/edit.html.erb
<h2>Edit Image</h2>

<%= render 'form'%>

app/views/images/new.html.erb
<h2>New Image for <%= @user.username %></h2>

<%= render 'form'%>

app/views/images/show.html.erb
<h1>Image Page</h1>
<br>
<%= image_tag(@image.avatar.url(:thumb)) %>

<%= @image.name%>
<%= @image.description%>
<hr>
<% if @image.comments.any? %>
  <% @image.comments.each do |comment| %>
    <p><%= comment.author %></p>
    <p><%= comment.content %></p>

    <% if is_admin? %>


      <%= link_to "Edit Comment", edit_image_comment_path(@image, comment) %> |
      <%= link_to "Delete this comment", image_comment_path(@image, comment),
              :data => {:confirm => "Are you sure?",
                :method => "delete"} %>

      <% end %>

  <br>
  <hr>
  <% end %>
<% else %>
<p>There are no comments yet!</p>
<% end %>
<%= link_to "Add Comment", new_image_comment_path(@image) %>